default_settings: null
behaviors:
  SeekerAgentV3:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        type: replay
        memory_size: 100
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
      curiosity: 
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: "3.0e-4"
    max_steps: 20000000
    keep_checkpoints: 5
    time_horizon: 128
    summary_freq: 20000
    threaded: true
